name: hopeapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.13
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  path: ^1.9.0
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.1
  http: ^1.2.2
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  app_settings: ^5.1.1
  permission_handler: ^11.3.1
  image_cropper: ^8.1.0
  firebase_app_check: ^0.3.1+7
  webview_flutter: ^4.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_cached_pdfview: ^0.4.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/ic_launcher.png"
  
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/ic_launcher_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/dummy/
